# Generated by Django 2.1.2 on 2019-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
